# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Definition

import flatbuffers

class proto_userint(object):
    __slots__ = ['_tab']

    # proto_userint
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # proto_userint
    def Useridx(self): return self._tab.Get(flatbuffers.number_types.Uint32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(0))
    # proto_userint
    def LoginCount(self): return self._tab.Get(flatbuffers.number_types.Uint32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(4))

def Createproto_userint(builder, useridx, loginCount):
    builder.Prep(4, 8)
    builder.PrependUint32(loginCount)
    builder.PrependUint32(useridx)
    return builder.Offset()
