# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Definition

import flatbuffers

class proto_header(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsproto_header(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = proto_header()
        x.Init(buf, n + offset)
        return x

    # proto_header
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # proto_header
    def Useridx(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

def proto_headerStart(builder): builder.StartObject(1)
def proto_headerAddUseridx(builder, useridx): builder.PrependUint32Slot(0, useridx, 0)
def proto_headerEnd(builder): return builder.EndObject()
