# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Definition

class responseResultType(object):
    unknown = 0
    pool_gold = 1
    pool_ruby = 2
    pool_ticket = 4
    pool_piece = 5
    pool_item = 6
    pool_bag = 7
    pool_condition = 8
    pool_count = 10
    pool_level = 11
    pool_time = 13
    over_time = 30
    over_quest = 31
    success = 127

