from WebApplication.Document.Protocol.Definition.E_Friend_Request_State import *
from WebApplication.Document.Protocol.Definition.proto_characterInfo import *
from WebApplication.Document.Protocol.Definition.proto_header import *
from WebApplication.Document.Protocol.Definition.proto_interest import *
from WebApplication.Document.Protocol.Definition.proto_onReadCharacters import *
from WebApplication.Document.Protocol.Definition.proto_onReadFriendList import *
from WebApplication.Document.Protocol.Definition.proto_onReadUserInfo import *
from WebApplication.Document.Protocol.Definition.proto_registAccount import *
from WebApplication.Document.Protocol.Definition.proto_responseFriendRequest import *
from WebApplication.Document.Protocol.Definition.proto_userInfo import *
from WebApplication.Document.Protocol.Definition.proto_userint import *
from WebApplication.Document.Protocol.Definition.proto_userInterest import *
from WebApplication.Document.Protocol.Definition.responseResultType import *
